networks:
  default:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.27.1.0/24

volumes:
    portainer:
    pgresdata:
    
# =====================Внешние сервисы окружения=====================
services:
  dozzle:
    image: amir20/dozzle
    container_name: dozzle
    restart: always
    networks:
    - default
    ports:
    - "8888:8080"
    environment:
    - DOZZLE_NO_ANALYTICS=true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  portainer-ce:
    image: portainer/portainer-ce:2.19.4
    container_name: portainer-ce
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    ports:
      - "9443:9443"
      - "8000:8000"

# ===================== Database =====================
  postgres:
    restart: always
    image: postgres:16.3
    ports:
      - 5432:5432
    env_file:
      - env/postgres.env
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
    #volumes:
    #  - pgresdata:/var/lib/postgresql/data

# ===================== Migration =====================

  postgres_init:
    image: postgres:16.3
    depends_on:
      - postgres
    env_file:
      - env/postgres.env
    volumes:
      - ./pg-db-init:/init-db
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      until pg_isready -h postgres -U postgres; do echo 'Waiting for database...'; sleep 2; done;
      psql -v ON_ERROR_STOP=1 -h postgres -U postgres -f /init-db/01__create_db_logs.sql
      " 

  db-migrations:
    image: ghcr.io/alekaz04/coinkeeper/migration-bundle:v0.0.1
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - env/backend.env

# ===================== Сервисы =====================
  backend:
    image: ghcr.io/alekaz04/coinkeeper/backend:v0.0.1
    restart: always    
    depends_on:
      - postgres
      - db-migrations
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    env_file:
      - env/backend.env