networks:
  default:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.27.2.0/24

volumes:
    portainer:
    pgresdata:

# ===================== Database =====================
services:
  postgres:
    restart: always
    image: postgres:16.3
    ports:
      - 5434:5432
    env_file:
      - env/postgres.env
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgresdata:/var/lib/postgresql/data

# ===================== Migration =====================
  postgres_init:
    image: postgres:16.3
    depends_on:
      - postgres
    env_file:
      - env/postgres.env
    volumes:
      - ./pg-db-init:/init-db
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "
      until pg_isready -h postgres -U postgres; do echo 'Waiting for database...'; sleep 2; done;
      psql -v ON_ERROR_STOP=1 -h postgres -U postgres -f /init-db/01__create_db_logs.sql
      " 

  db-migrations:
    image: ghcr.io/alekaz04/coinkeeper/migration-bundle:dev
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - env/backend.env

# ===================== Сервисы =====================
  backend:
    image: ghcr.io/alekaz04/coinkeeper/backend:dev
    restart: always    
    depends_on:
      - postgres
      - db-migrations
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    env_file:
      - env/backend.env